import {
  House,
  GraduationCap,
  Users,
  BookOpen,
  UserCircle,
  LayoutGrid,
  BookMarked,
  CalendarDays,
  ClipboardCheck,
  PenSquare,
  BellRing,
  Bus,
  Building2,
  ChevronDown,
} from "lucide-react";
export const navbarAssets = [
  {
    to: "/home",
    icon: House,
    title: "Home",
    isGroup: false,
  },
  {
    icon: GraduationCap,
    title: "Students",
    isGroup: true,
    groupItems: [
      { title: "All Students", to: "/allstudents" },
      { title: "Student Details", to: "/studentdetails" },
    ],
    chevron: ChevronDown,
  },
  {
    icon: Users,
    title: "Teacher",
    isGroup: true,
    groupItems: [{ title: "All Teachers", to: "/allteachers" }],
    chevron: ChevronDown,
  },
  { to: "/library", icon: BookOpen, title: "Library", isGroup: false },
  { to: "/account", icon: UserCircle, title: "Account", isGroup: false },
  { to: "/class", icon: LayoutGrid, title: "Class", isGroup: false },
  { to: "/subject", icon: BookMarked, title: "Subject", isGroup: false },
  { to: "/routine", icon: CalendarDays, title: "Routine", isGroup: false },
  {
    to: "/attendance",
    icon: ClipboardCheck,
    title: "Attendance",
    isGroup: false,
  },
  { to: "/exam", icon: PenSquare, title: "Exam", isGroup: false },
  { to: "notice", icon: BellRing, title: "Notice", isGroup: false },
  { to: "bus", icon: Bus, title: "Bus", isGroup: false },
  { to: "hostel", icon: Building2, title: "Hostel", isGroup: false },
];
