import {
  House,
  GraduationCap,
  Users,
  BookOpen,
  UserCircle,
  LayoutGrid,
  BookMarked,
  CalendarDays,
  ClipboardCheck,
  PenSquare,
  BellRing,
  Bus,
  Building2,
  ChevronDown,
} from "lucide-react";
export const navbarAssets = [
  { icon: House, title: "Home", isGroup: false },
  {
    icon: GraduationCap,
    title: "Students",
    isGroup: true,
    groupItems: [{ title: "All Students" }, { title: "Student Details" }],
    chevron: ChevronDown,
  },
  {
    icon: Users,
    title: "Teacher",
    isGroup: true,
    groupItems: [{ title: "All Teachers" }],
    chevron: ChevronDown,
  },
  { icon: BookOpen, title: "Library", isGroup: false },
  { icon: UserCircle, title: "Account", isGroup: false },
  { icon: LayoutGrid, title: "Class", isGroup: false },
  { icon: BookMarked, title: "Subject", isGroup: false },
  { icon: CalendarDays, title: "Routine", isGroup: false },
  { icon: ClipboardCheck, title: "Attendance", isGroup: false },
  { icon: PenSquare, title: "Exam", isGroup: false },
  { icon: BellRing, title: "Notice", isGroup: false },
  { icon: Bus, title: "Bus", isGroup: false },
  { icon: Building2, title: "Hostel", isGroup: false },
];
